DATASET:
  NAME: "vg"
  MODE: "benchmark"
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 1
MODEL:
  WEIGHT_IMG: "catalog://ImageNetPretrained/MSRA/R-101"
  WEIGHT_DET: "checkpoints/vg_benchmark_object/R-101-C4/faster_rcnn/BatchSize_6/Base_LR_0.005/checkpoint_0099999.pth"
  RELATION_ON: True
  ALGORITHM: "sg_baseline"
  USE_FREQ_PRIOR: False
  BACKBONE:
    CONV_BODY: "R-101-C4"
    FREEZE_PARAMETER: True
  RPN:
    FREEZE_PARAMETER: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    DETECTIONS_PER_IMG: 64
  ROI_BOX_HEAD:
    NUM_CLASSES: 151
    FREEZE_PARAMETER: True
  ROI_RELATION_HEAD:
    FILTER_NON_OVERLAP: False
    BATCH_SIZE_PER_IMAGE: 256
    TRIPLETS_PER_IMG: 100
    NUM_CLASSES: 51
    IMP_FEATURE_UPDATE_STEP: 2
    MSDN_FEATURE_UPDATE_STEP: 2
    GRCNN_FEATURE_UPDATE_STEP: 2
    GRCNN_SCORE_UPDATE_STEP: 2
SOLVER:
  BASE_LR: 5e-3
  MAX_ITER: 30000
  STEPS: (15000,25000)
  CHECKPOINT_PERIOD: 1000
